### ISSUE TITLE
syntaxerror import

### ISSUE THREAD

**Issue by wannesdemaeght** [HyperCubeProject/binance-api-node#11]
When trying this sample in node js:

`import Binance from 'binance-api-node'
const client = Binance()

client.time().then(time => console.log(time))`

I get this error:

`import Binance from 'binance-api-node'
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

Upon investigating on the net, I found that node js doesn't natively support ES6.
One workaround is to use require instead:

`const Binance = require('binance-api-node')
const client = Binance()

client.time().then(time => console.log(time))`

But this then gets me this error:

`const client = Binance()
               ^

TypeError: Binance is not a function
    at Object.<anonymous> (C:\Trader\Logic\Random\test.js:9:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3`

Another workaround would be to use babel, but I don't have any knowledge regarding that.
Is there an easy fix?

Thanks,
Wannes

**Comment by balthazar** [comment]
```js
const Binance = require('binance-api-node').default
```
