### ISSUE TITLE
Error running basic program (possible newbie error)

### ISSUE THREAD

**Issue by gmanroney** [HyperCubeProject/binance-api-node#168]
I'm working with nodejs on Windows 10.
Installed package with

` npm install binance-api-node
`
When I tried to run 

```
import Binance from 'binance-api-node'

const client = Binance()

// Authenticated client, can make signed calls
const client2 = Binance({
  apiKey: 'xxx',
  apiSecret: 'xxx',
  getTime: xxx // time generator function, optional, defaults to () => Date.now()
})

client.time().then(time => console.log(time))
```

got error:
```

(function (exports, require, module, __filename, __dirname) { import Binance from 'binance-api-node'
                                                                     ^^^^^^^
SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)ot error

```
Any idea where I went wrong?

**Comment by balthazar** [comment]
One google query would have solved your issue

https://medium.com/@JedaiSaboteur/import-export-babel-and-node-a2e332d15673

**Comment by LucemAnb** [comment]
> One google query would have solved your issue
> 
> https://medium.com/@JedaiSaboteur/import-export-babel-and-node-a2e332d15673

this issue is the first result after one google query

**Comment by balthazar** [comment]
@LucemAnb You should probably learn how to properly debug stacktraces if that is the case.
