### ISSUE TITLE
can't get the example running

### ISSUE THREAD

**Issue by divramod** [HyperCubeProject/binance-api-node#30]
Hey, 

i really like that you ported the project to async.
But i cant get it running.
What is it, i have to do to compile the project correctly?

After i installed binance-api.node and running a server.js file with the following code

    import Binance from 'binance-api-node'

i get the error message

```
>node server.js                                                                                               [±master ●●]
/home/mod/code/projects/traders-friend/api/app/server.js:1
(function (exports, require, module, __filename, __dirname) { import Binance from 'binance-api-node'
                                                                     ^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

i am running node version 9.0.0.
thx in advance!

**Comment by balthazar** [comment]
You need babel to support the es6 imports. Otherwise just use a default commonjs require

```js
const Binance = require('binance-api-node').default
```
