### ISSUE TITLE
Error: Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by jsappme** [HyperCubeProject/binance-api-node#69]
any idea why do I get this error?
```
{ Error: Filter failure: PRICE_FILTER
    at C:\Users\herve\OneDrive\Documents\GitHub\xxx\node_modules\binance-api-node\dist\http.js:47:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: -1013 }
```

**Comment by balthazar** [comment]
Most likely due to the query getting passed to your call. This is an API error, not one of this library
