### ISSUE TITLE
Error: Invalid symbol.

### ISSUE THREAD

**Issue by bennyn** [HyperCubeProject/binance-api-node#7]
Today I tried to sell XLM using **binance-api-node**. I tried to execute it this way:

```javascript
const Binance = require('binance-api-node').default;

const client = Binance({
  apiKey: process.env.BINANCE_API_KEY,
  apiSecret: process.env.BINANCE_API_SECRET
});

const order = { 
  symbol: 'XLM',
  side: 'SELL',
  type: 'LIMIT',
  quantity: 48,
  price: 0.00031337
};

client.order(order).then(response => console.log('Success'));
```

Unfortunately I am always receiving the following error:

> Error: Invalid symbol.
    at D:\dev\projects\bennyn\trading-bot-framework\node_modules\binance-api-node\dist\http.js:47:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

What am I doing wrong? 

I logged `error.code` (https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md) but it's `undefined`. 😢

**Comment by bennyn** [comment]
Ok, I found my mistake! I needed to replace my symbol `XLM` with `XLMETH`. 🙈
